name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lean-action:
    name: Lean Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
